{% set name = "mms-python-adapter" %}
{% set version = "1.2.5" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dded9d59246be03a8fb1f299b1b70b2dbf85dcea87076316e65d23f7bbc7fa7d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - mms-python-client <4

test:
  requires:
    - python {{ python_min }}
  imports:
    - mms_python_adapter

about:
  home: http://openmbee.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: QOL wrapper for mms-python-client

extra:
  recipe-maintainers: 
    - HuiJun
    - dlamoris
